### PR TITLE
Include the filename of the cia, and pad the titleID to display in the standard format.

### PR DESCRIPTION
**Pull request by ksanislo**
There's some minor tweaking to the posted comments, still no verification of the titleID info yet...

Posts will look like this:
`QR Code for [ECITool.cia (569.8 kB)](https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl=https://github.com/BernardoGiordano/ECITool/releases/download/1.3full/ECITool.cia&choe=UTF-8.png)

---

Title ID: 0x000400000EC10000
Short Description: ECI Tool
Long Description: ECI Tool
Publisher: Bernardo Giordano

---

_3DS QR Bot by /u/Im_Soul_
`

### CODE REVIEW

**Comment by denali999** [comment]
You need a double space at the end of every line before moving to the newline
So 
`'Title ID: ' + finished[3] + '\n' +\` 
becomes 
`'Title ID: ' + finished[3] + '   \n' +\`

**Comment by ksanislo** [comment]
Oh, good catch... I wasn't aware of that, I'll re-edit to fix things. Neither python or reddit posts are apparently my forte.

**Comment by ksanislo** [comment]
Alright, it makes [proper looking posts now](https://www.reddit.com/r/test/comments/4ogt4s/test_post/d4cfjgs)

**Comment by ksanislo** [comment]
I've added support for github releases where there are more than one .cia file posted, as well as only adding the .cia QR for files which match a titleID starting with 0x0004 (3DS platform).

The posting format will [look like this](https://www.reddit.com/r/test/comments/4oh8hs/qr_bot_test_post/d4ckg9w)

Also, in real world use, that .zip with the invalid ID wouldn't actually be shown, that was just because I wanted a quick test case for multiple files.

**Comment by denali999** [comment]
Some problems. 

```
if qrlist is not None:
    for qrentry in qrlist:
```

However, at the very least `make_qr()` returns an empty list, meaning the commenting portion would return an `IndexError`. This can be fixed easily by replacing `if qrlist is not None:` with `if not qrlist:`, as empty lists are considered `False` in Boolean Context

**Comment by ksanislo** [comment]
@thesouldemon Are you sure about that? Python calls it a NoneType object when it doesn't come back with a list.

`TypeError: 'NoneType' object is not iterable`

**Comment by denali999** [comment]
EDIT: I think I figured out why it doesn't work for that repo. It's tagged as 'pre-release' (where [this](https://github.com/Cruel/freeShop/releases/tag/1.2) is tagged as "latest release", which I think messed with the api scheme. Still going to bed though

I don't even know what's going on anymore. 
`bool(qrlist))` returns `False`,
I don't know if it matters (because i cant test the code, see below), but I would rather use `if not qrlist`, as it is the "pythonic" way 

However I can't even seem to get [this](https://github.com/RedInquisitive/Super-Haxagon/releases/tag/0.1#test) repo to work with the bot, using any version of the code. The github api just returns a dict element `"message": "Not Found"`, yet it works for any other repo. I'm going to bed, I'll try more tomorrow.

**Comment by ksanislo** [comment]
I had the return from make_qr at the wrong intent level (argh! stupid python! whitespace shouldn't matter!) so now it works as expected using `if qrlist:` alone. And the one dual .cia test post fails because its marked pre-release so github won't show it for your hardcoded /release/latest method. I'm not sure of a better way to fix that yet...

**Comment by denali999** [comment]
I changed the way the latest release is found. It now gets the latest tag from the `/repos/:owner/:repo/git/refs/tags` endpoint. It then searches for a release for a certain tag name with the `/repos/:owner/:repo/releases/tags/:tag` endpoint. The data output is the same. This should now work for any "type" of release; pre-release, latest, etc

**Pull request closed without merging**
